apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-worker-java
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-java
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: votes_unprocessed
      target:
        type: AverageValue
        averageValue: 10