apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  prometheus.yaml: |
    global:
      scrape_interval:     15s # Default scrape interval
    scrape_configs:
      - job_name: 'prometheus' # Job to scrape Prometheus metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'worker-java'
        metrics_path: '/actuator/prometheus' # Job to scrape application metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['worker-java:8080']
---