apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: worker-java-monitor-selector
  name: worker-java-monitor
  namespace: default
spec:
  endpoints:
  - interval: 10s
    targetPort: 8080
    path: /actuator/prometheus
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: "worker-java"