apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker-java
  name: worker-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-java
  template:
    metadata:
      labels:
        app: worker-java
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - image: examplevotingapp_worker_java
        imagePullPolicy: Never
        name: worker-java
        ports:
        - containerPort: 8080
          name: worker-java
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "kubernetes"
        livenessProbe:
          httpGet:
            path: "/actuator/health/liveness"
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/actuator/health/readiness"
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker-java
  name: worker-java
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31002
  selector:
    app: worker-java